name: warm-cache

on:
  push:
    branches:
      - main

jobs:
  warm-cache-debug:
    runs-on: macos-26
    permissions:
      contents: read
      id-token: write
    env:
      MISE_HTTP_TIMEOUT: 120
      MISE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-macos
      - run: make warm-cache
